export type ProviderConfig = {
  id: string;
  name: string;
  domains: string[];
  category: string;
  website: string;
  subjectKeywords: string[];
};

export const mailboxSignalKeywords = [
  "invoice",
  "receipt",
  "subscription",
  "membership",
  "renewal",
  "billing",
  "payment",
  "charged",
  "premium",
  "plan",
  "membership",
];

export const providerCatalog: ProviderConfig[] = [
  {
    id: "netflix",
    name: "Netflix",
    domains: ["netflix.com"],
    category: "Video & TV",
    website: "https://www.netflix.com",
    subjectKeywords: ["receipt", "billing", "payment"],
  },
  {
    id: "spotify",
    name: "Spotify",
    domains: ["spotify.com"],
    category: "Music",
    website: "https://www.spotify.com",
    subjectKeywords: ["receipt", "premium", "payment"],
  },
  {
    id: "youtube-premium",
    name: "YouTube Premium",
    domains: ["youtube.com", "google.com"],
    category: "Video & TV",
    website: "https://www.youtube.com/premium",
    subjectKeywords: ["receipt", "membership", "purchase"],
  },
  {
    id: "disney-plus",
    name: "Disney+",
    domains: ["disneyplus.com", "disney.com"],
    category: "Video & TV",
    website: "https://www.disneyplus.com",
    subjectKeywords: ["receipt", "invoice", "subscription"],
  },
  {
    id: "hulu",
    name: "Hulu",
    domains: ["hulu.com"],
    category: "Video & TV",
    website: "https://www.hulu.com",
    subjectKeywords: ["receipt", "billing", "payment"],
  },
  {
    id: "prime-video",
    name: "Prime Video",
    domains: ["amazon.com", "amazon.co.uk", "amazon.de"],
    category: "Video & TV",
    website: "https://www.primevideo.com",
    subjectKeywords: ["subscription", "renewal", "membership"],
  },
  {
    id: "apple-icloud",
    name: "iCloud+",
    domains: ["apple.com", "icloud.com"],
    category: "Cloud Storage",
    website: "https://www.apple.com/icloud",
    subjectKeywords: ["receipt", "invoice", "subscription"],
  },
  {
    id: "google-one",
    name: "Google One",
    domains: ["google.com"],
    category: "Cloud Storage",
    website: "https://one.google.com",
    subjectKeywords: ["receipt", "google one", "storage"],
  },
  {
    id: "dropbox",
    name: "Dropbox",
    domains: ["dropbox.com"],
    category: "Cloud Storage",
    website: "https://www.dropbox.com",
    subjectKeywords: ["receipt", "invoice", "plan"],
  },
  {
    id: "adobe",
    name: "Adobe Creative Cloud",
    domains: ["adobe.com"],
    category: "Software",
    website: "https://www.adobe.com/creativecloud.html",
    subjectKeywords: ["invoice", "order", "receipt"],
  },
  {
    id: "chatgpt-plus",
    name: "ChatGPT Plus",
    domains: ["openai.com"],
    category: "AI Tools",
    website: "https://chatgpt.com",
    subjectKeywords: ["receipt", "invoice", "subscription"],
  },
  {
    id: "anthropic",
    name: "Claude",
    domains: ["anthropic.com"],
    category: "AI Tools",
    website: "https://www.anthropic.com",
    subjectKeywords: ["receipt", "invoice", "subscription"],
  },
  {
    id: "midjourney",
    name: "Midjourney",
    domains: ["midjourney.com"],
    category: "AI Tools",
    website: "https://www.midjourney.com",
    subjectKeywords: ["receipt", "invoice", "membership"],
  },
  {
    id: "cursor",
    name: "Cursor",
    domains: ["cursor.com", "cursor.sh"],
    category: "Software",
    website: "https://www.cursor.com",
    subjectKeywords: ["receipt", "invoice", "subscription"],
  },
  {
    id: "figma",
    name: "Figma",
    domains: ["figma.com"],
    category: "Software",
    website: "https://www.figma.com",
    subjectKeywords: ["invoice", "receipt", "plan"],
  },
  {
    id: "notion",
    name: "Notion",
    domains: ["notion.so"],
    category: "Software",
    website: "https://www.notion.so",
    subjectKeywords: ["receipt", "invoice", "subscription"],
  },
  {
    id: "canva",
    name: "Canva",
    domains: ["canva.com"],
    category: "Software",
    website: "https://www.canva.com",
    subjectKeywords: ["receipt", "invoice", "canva pro"],
  },
  {
    id: "office-365",
    name: "Microsoft 365",
    domains: ["microsoft.com", "office.com"],
    category: "Software",
    website: "https://www.microsoft.com/microsoft-365",
    subjectKeywords: ["invoice", "receipt", "subscription"],
  },
  {
    id: "slack",
    name: "Slack",
    domains: ["slack.com"],
    category: "Software",
    website: "https://www.slack.com",
    subjectKeywords: ["invoice", "receipt", "billing"],
  },
  {
    id: "zoom",
    name: "Zoom",
    domains: ["zoom.us"],
    category: "Software",
    website: "https://www.zoom.us",
    subjectKeywords: ["invoice", "receipt", "billing"],
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    domains: ["github.com"],
    category: "Software",
    website: "https://github.com/features/copilot",
    subjectKeywords: ["receipt", "invoice", "billing"],
  },
  {
    id: "new-york-times",
    name: "The New York Times",
    domains: ["nytimes.com"],
    category: "News",
    website: "https://www.nytimes.com",
    subjectKeywords: ["subscription", "receipt", "billing"],
  },
  {
    id: "wall-street-journal",
    name: "The Wall Street Journal",
    domains: ["wsj.com"],
    category: "News",
    website: "https://www.wsj.com",
    subjectKeywords: ["subscription", "receipt", "billing"],
  },
  {
    id: "medium",
    name: "Medium",
    domains: ["medium.com"],
    category: "News",
    website: "https://www.medium.com",
    subjectKeywords: ["receipt", "membership", "payment"],
  },
  {
    id: "economist",
    name: "The Economist",
    domains: ["economist.com"],
    category: "News",
    website: "https://www.economist.com",
    subjectKeywords: ["subscription", "invoice", "receipt"],
  },
  {
    id: "linkedin-premium",
    name: "LinkedIn Premium",
    domains: ["linkedin.com"],
    category: "Career",
    website: "https://www.linkedin.com/premium",
    subjectKeywords: ["receipt", "invoice", "subscription"],
  },
  {
    id: "grammarly",
    name: "Grammarly",
    domains: ["grammarly.com"],
    category: "Software",
    website: "https://www.grammarly.com",
    subjectKeywords: ["receipt", "invoice", "premium"],
  },
  {
    id: "1password",
    name: "1Password",
    domains: ["1password.com"],
    category: "Security",
    website: "https://1password.com",
    subjectKeywords: ["receipt", "invoice", "subscription"],
  },
  {
    id: "nordvpn",
    name: "NordVPN",
    domains: ["nordvpn.com"],
    category: "Security",
    website: "https://nordvpn.com",
    subjectKeywords: ["receipt", "invoice", "renewal"],
  },
  {
    id: "duolingo",
    name: "Duolingo",
    domains: ["duolingo.com"],
    category: "Education",
    website: "https://www.duolingo.com",
    subjectKeywords: ["receipt", "invoice", "super duolingo"],
  },
  {
    id: "peloton",
    name: "Peloton",
    domains: ["onepeloton.com"],
    category: "Health & Fitness",
    website: "https://www.onepeloton.com",
    subjectKeywords: ["receipt", "membership", "billing"],
  },
  {
    id: "strava",
    name: "Strava",
    domains: ["strava.com"],
    category: "Health & Fitness",
    website: "https://www.strava.com",
    subjectKeywords: ["receipt", "subscription", "premium"],
  },
  {
    id: "myfitnesspal",
    name: "MyFitnessPal",
    domains: ["myfitnesspal.com"],
    category: "Health & Fitness",
    website: "https://www.myfitnesspal.com",
    subjectKeywords: ["receipt", "premium", "subscription"],
  },
  {
    id: "headspace",
    name: "Headspace",
    domains: ["headspace.com"],
    category: "Health & Fitness",
    website: "https://www.headspace.com",
    subjectKeywords: ["receipt", "subscription", "renewal"],
  },
  {
    id: "calm",
    name: "Calm",
    domains: ["calm.com"],
    category: "Health & Fitness",
    website: "https://www.calm.com",
    subjectKeywords: ["receipt", "subscription", "renewal"],
  },
  {
    id: "shopify",
    name: "Shopify",
    domains: ["shopify.com"],
    category: "Business",
    website: "https://www.shopify.com",
    subjectKeywords: ["invoice", "receipt", "billing"],
  },
  {
    id: "mailchimp",
    name: "Mailchimp",
    domains: ["mailchimp.com"],
    category: "Business",
    website: "https://www.mailchimp.com",
    subjectKeywords: ["invoice", "receipt", "billing"],
  },
  {
    id: "squarespace",
    name: "Squarespace",
    domains: ["squarespace.com"],
    category: "Business",
    website: "https://www.squarespace.com",
    subjectKeywords: ["invoice", "receipt", "billing"],
  },
  {
    id: "wix",
    name: "Wix",
    domains: ["wix.com"],
    category: "Business",
    website: "https://www.wix.com",
    subjectKeywords: ["invoice", "receipt", "billing"],
  },
  {
    id: "webflow",
    name: "Webflow",
    domains: ["webflow.com"],
    category: "Business",
    website: "https://webflow.com",
    subjectKeywords: ["invoice", "receipt", "billing"],
  },
  {
    id: "ghost",
    name: "Ghost",
    domains: ["ghost.org"],
    category: "Business",
    website: "https://ghost.org",
    subjectKeywords: ["invoice", "receipt", "billing"],
  },
  {
    id: "heroku",
    name: "Heroku",
    domains: ["heroku.com"],
    category: "Business",
    website: "https://www.heroku.com",
    subjectKeywords: ["invoice", "receipt", "billing"],
  },
  {
    id: "netlify",
    name: "Netlify",
    domains: ["netlify.com"],
    category: "Business",
    website: "https://www.netlify.com",
    subjectKeywords: ["invoice", "receipt", "billing"],
  },
  {
    id: "vercel",
    name: "Vercel",
    domains: ["vercel.com"],
    category: "Business",
    website: "https://vercel.com",
    subjectKeywords: ["invoice", "receipt", "billing"],
  },
  {
    id: "digitalocean",
    name: "DigitalOcean",
    domains: ["digitalocean.com"],
    category: "Business",
    website: "https://www.digitalocean.com",
    subjectKeywords: ["invoice", "receipt", "billing"],
  },
  {
    id: "stripe",
    name: "Stripe",
    domains: ["stripe.com"],
    category: "Payments",
    website: "https://stripe.com",
    subjectKeywords: ["invoice", "receipt", "payment"],
  },
  {
    id: "paypal",
    name: "PayPal",
    domains: ["paypal.com"],
    category: "Payments",
    website: "https://www.paypal.com",
    subjectKeywords: ["receipt", "payment", "subscription"],
  },
  {
    id: "wise",
    name: "Wise",
    domains: ["wise.com"],
    category: "Payments",
    website: "https://wise.com",
    subjectKeywords: ["receipt", "payment", "invoice"],
  },
  {
    id: "uber",
    name: "Uber One",
    domains: ["uber.com"],
    category: "Food & Transport",
    website: "https://www.uber.com",
    subjectKeywords: ["subscription", "receipt", "membership"],
  },
  {
    id: "deliveroo",
    name: "Deliveroo Plus",
    domains: ["deliveroo.com"],
    category: "Food & Transport",
    website: "https://deliveroo.co.uk",
    subjectKeywords: ["subscription", "membership", "receipt"],
  },
  {
    id: "instacart",
    name: "Instacart+",
    domains: ["instacart.com"],
    category: "Food & Transport",
    website: "https://www.instacart.com",
    subjectKeywords: ["subscription", "membership", "receipt"],
  },
  {
    id: "dashpass",
    name: "DashPass",
    domains: ["doordash.com"],
    category: "Food & Transport",
    website: "https://www.doordash.com",
    subjectKeywords: ["subscription", "membership", "receipt"],
  },
  {
    id: "hellofresh",
    name: "HelloFresh",
    domains: ["hellofresh.com", "hellofresh.co.uk"],
    category: "Food & Transport",
    website: "https://www.hellofresh.com",
    subjectKeywords: ["receipt", "invoice", "order"],
  },
  {
    id: "blue-apron",
    name: "Blue Apron",
    domains: ["blueapron.com"],
    category: "Food & Transport",
    website: "https://www.blueapron.com",
    subjectKeywords: ["receipt", "invoice", "order"],
  },
  {
    id: "audible",
    name: "Audible",
    domains: ["audible.com", "amazon.com"],
    category: "Education",
    website: "https://www.audible.com",
    subjectKeywords: ["membership", "receipt", "renewal"],
  },
  {
    id: "masterclass",
    name: "MasterClass",
    domains: ["masterclass.com"],
    category: "Education",
    website: "https://www.masterclass.com",
    subjectKeywords: ["subscription", "receipt", "billing"],
  },
  {
    id: "coursera",
    name: "Coursera",
    domains: ["coursera.org"],
    category: "Education",
    website: "https://www.coursera.org",
    subjectKeywords: ["subscription", "receipt", "payment"],
  },
  {
    id: "udemy",
    name: "Udemy",
    domains: ["udemy.com"],
    category: "Education",
    website: "https://www.udemy.com",
    subjectKeywords: ["receipt", "order", "purchase"],
  },
  {
    id: "skillshare",
    name: "Skillshare",
    domains: ["skillshare.com"],
    category: "Education",
    website: "https://www.skillshare.com",
    subjectKeywords: ["membership", "receipt", "billing"],
  },
];

export const providerById = new Map(providerCatalog.map((provider) => [provider.id, provider]));
